### ISSUE TITLE
Error starting stream, fetch an active user first - kKFAPIClientErrorDomain

### ISSUE THREAD

**Issue by 4netinteractive** [Kickflip/kickflip-ios-sdk#21]
Hi,

We're a paying customer and have launched an app in de appstore with kickflip in it. But although we had issues with the webservice last month, it seems that it has returned again.

If we want to start a livestream, we get this error: "Error starting stream: Fetch an active user first." 
And after that "kKFAPIClientErrorDomain error 105". We haven't changed our code, but it's not working anymore. 
This afternoon I also tried it with the new v1.3 kickflip sdk, but we're experiencing the same issue. Can you please look into this issue?

**Comment by chrisballinger** [comment]
It's because Amazon changed the IAM user limit which broke our old backend and forced us to migrate to their new STS federated tokens. The old API endpoint is deprecated because it still creates new IAM users (to prevent breaking existing apps), but it now requires to periodically purge IAM users for the free tier customers.

However, we have identified a bug that is still creating new IAM users on the new 1.2 API endpoint and will be fixing it momentarily.

**Comment by chrisballinger** [comment]
@4netinteractive Okay the backend problem has been resolved and now everything should work properly for the new v1.3 SDK. 

Since you are a paying customer the old SDK / API endpoint will continue to work for a few weeks, but we will be deprecating the old API endpoint very soon so please upgrade as soon as possible. 

Let me know if you're having any further issues. Thanks!
