### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [Kickflip/kickflip-ios-sdk#45]
Trial didn't work. Many problems with the demo app. Code hasn't being touched for a while.

**Comment by boztalay** [comment]
I'm wondering the same thing, the current SDK (1.3) doesn't even build anymore.

**Comment by nicholas** [comment]
This main repo is pretty dead, yes, but that isn't solely on Chris Ballinger imo. There's lots of forks, including ours (https://github.com/twinenginelabs/kickflip-ios-sdk) that have things working (at least for us). It's on us though to get that into PRs, which I failed at. Got too busy with client work and a newborn, and I progressed the project to the point where opening proper PRs for each change would take a lot of effort. I'm considering opening one big one that we can modify to an agreeable state.

Before we (TEL) do that though, we're experimenting with Video Toolbox integration. Seems like a good place to make the switch back to main.

**Comment by nicholas** [comment]
Giant smorgasbord of a pull request created (#48), woohoo!

**Comment by ivarvermeulen** [comment]
At this moment the kickflip backend seems to be down. We are relying on this service!

**Comment by GuilhermeMedeiros** [comment]
good job @nicholas! maybe you should create your own repo, they will take quite some time to accept your pull request

**Comment by kohey18** [comment]
I found that kickflip.io is down from yesterday.
I also relying on this OSS, so I'm so surprised.

**Comment by duanmua** [comment]
FYI it seems the DNS registration for kickflip.io expired, thus causing these issues

**Comment by duanmua** [comment]
@nicholas I noticed your app is still up and running. Did y'all at TEL create your own backend services? Or did Kickflip set you up with your own domain?

**Comment by nicholas** [comment]
@duanmua Well, it's running, but starting streams is currently busted, actually. We're in the process of migrating over to the Open Kickflip derivative. When that's available, I'll chime back in here.

**Comment by nicholas** [comment]
Ok, spun up a new repo @ https://github.com/OpenKickflip/openkickflip-ios-sdk with everything under one roof. There's still more to do and I've only tested it against my own system so we may have some things to work through to ensure it works for everyone. I'll continue as I have time/availability.

One thing to note, I switched out the AWS Cognito credential provider in place of just using your own static keys for now. Will get to that down the road. Also, the S3 URL paths have changed a bit .. guessing the API was injecting the stream's GUID into the upload URL. Probably a good idea to wait-on/provide a fix for that for production since (I'm assuming) it's susceptible to overwriting content atm.

**Comment by GuilhermeMedeiros** [comment]
Good job @nicholas!

**Comment by chrisballinger** [comment]
Not dead yet!

https://www.youtube.com/watch?v=Jdf5EXo6I68

**Comment by chrisballinger** [comment]
p.s. thank you for all the fine work!

**Comment by nicholas** [comment]
Awesome, thanks for chiming in. Let me know how you want to work with Open Kickflip .. only fair you get a chance to make some sense of that direction and how it could fit into your plans. Get in touch with me whenever!
